### ISSUE TITLE
Oprava domácího úkolu: Jen pár věcí k dokonalosti

### ISSUE THREAD

**Issue by mohlerit** [armvdd/ukol-01#1]
Ahoj Hanko,
super práce. Tvá stránka je super :-). Každopádně něco jsem našel.

**Začneme s index.html**
- Ná řádku 2 má `lang="en"` to je vhodné přepsat na `lang="cs"`, protože stránky jsou v češtině a ne v angličtině.
- Na řádku 14 používáš width a height, kde nastavuješ  hodnotu v pixelech. To bohužel není validní hodnota pro atribut `width` nebo `height`. Pokud ale tenot zápis uděláš v CSS, tak už validní bude. U tagu `img` to sice funguje, ale validátorem to neprojde. Přidej id obrázku a přepiš hodnoty do CSS.
- Na řádku 75 máš u obrázků id a velikost nastavuješ přes CSS, ale naopak ti zde chybí povinný atribut `alt`, který má za úkol popsat obrázek v případě, že se obrázek nenačte nebo pro neviddomé. Vždy je dobré alt vypsat i kdyby tam mělo být jen "Facebook Ikona".
- Na řádku 29 zbytečně `ul` obaluješ do tagu `p`. Tag `ul` je "rovný" tagu `p` a nemusí být jím obalen. Je to odrářkový seznam nebo odstavec. Nepotřebuješ mít v odstavci seznam. Na obalování je případně vhodné používat tag `div`.

Odkaz na validátor W3: https://validator.w3.org/nu/?doc=https%3A%2F%2Farmvdd.github.io%2Fukol-01%2F%23zaj

**style.css**
- Na řádku 6 máš použité `background-collor: white`. Koukal jsme se, že používáš hexadecimální zápis a já doporuřuji pokud je to možné se držet jednoho stylu. Psaní barev slovy se v praxi nepoužívá. Raději použij `#ffffff`
- Dále jsem si všiml, že někdy používáš v hexadecimálním zápisu barev malé a někdy velké písmena. Ničemu to nevadí, ale je také dobré to sjednotit. Kód pak vypadá lépe.
- A když už jsme u vzhledu kódu, tak podotknu že za `:` někde máš mezeru a někde ne. Najdi si svůj styl a jednotně ho drž. Vizuálně to udělá hodně i když na funkčnost to nemá vliv.
- Nakonec jsem si všiml, že u tagu `header` a `footer` používáš třídu `hlavicka` nebo `paticka`. V tomto případě to není vůbec nutné.
```
footer{
    background-color: #4f5b7c;
    margin: 0;
    padding: 15px;
}
.paticka p{
    margin: 0;
    padding: 0;
    color: #B8BEBF;
    text-align: center;
}
```
se dá zapsat jako 
```
footer{
    background-color: #4f5b7c;
    margin: 0;
    padding: 15px;
}
footer p{
    margin: 0;
    padding: 0;
    color: #B8BEBF;
    text-align: center;
}
```

## Pro udělení hodnocení je nutné:
- [x] Změnit hodnotu atributu `lang` z `en` na `cs`
- [x] Odstranit atributy `width` a `height` z tagu `img`
- [x] Zbavit se obalení tagu `ul` tagem `p`

Nakonec si zkontroluj, že ti stránka projde skrz validátor W3, která najdeš tady: https://validator.w3.org/ 
Čistý a validné kód je vždy dobrou vizitkou.

**Comment by armvdd** [comment]
Ahoj!
Děkuju za poznámky, vše jsem opravila :)
K rozdílům malá / velká písmena došlo kvůli kopírování některých kódů barvy z ColorZilla, ta je má všechna velká. Dám na to do příště pozor :)
